Module2 task1
htmlacademy-adaptive/1734813-sedona-28 pull request #3
Opened 2023-04-08 17:21 UTC by savven0k

2023-04-09 11:47 UTC, ZerdoX-x commented
https://github.com/htmlacademy-adaptive/1734813-sedona-28/actions/runs/4646292133/jobs/8222624035

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/49815452/230770658-551d6fd1-84fa-4bcf-9954-9692e56ed58f.png">

Ты открыл PR с кодом, его проверила уже заранее настроенная сборка проекта. Как ты видишь, она падает с ошибкой. Попробуй разобраться, в чём может быть причина.

2023-04-09 11:51 UTC, ZerdoX-x commented
Также в историю коммитов попал предыдущий коммит. Это произошло потому что ты сделал checkout от локальной ветки, которая содержит этот (первый) коммит с наставником, и не сделал pull с удалённого (гитхаб) репозитория, где этот код уже принят. На звонке на этот момент тоже посмотрим.

2023-04-10 13:45 UTC, ZerdoX-x requested changes
Это первая итерация. Используя советы из ревью, пожалуйста проверь самостоятельно все страницы. Начнём с простого. После чего будет вторая итерация.

2023-04-10 13:45 UTC, ZerdoX-x commented on catalog.html
> +      <img class="main-header__logo-image" src="img/logotype-phone.svg" width="185px" height="96px"
1. `src="img/logotype-phone.svg"` - почему ты выбрал относительный, а не абсолютный путь для картинки? если эту шапку скопипастить на другую страницу, которая будет лежать по другому пути, то картинка потеряется
2. Прогони пожалуйста все страницы через валидатор. `width="185px"` - следующие грубые ошибки в разметке в ревью я не буду упоминать.

2023-04-10 13:45 UTC, ZerdoX-x commented on catalog.html
> +    <a class="main-header__logo">
У `a` нет ссылки (`href`), валидатор должен был это заметить.

2023-04-10 13:45 UTC, ZerdoX-x commented on catalog.html
> +        <span class="vissualy-hidden">Открыть меню</span>
Опечатка в названии класса

2023-04-10 13:45 UTC, ZerdoX-x commented on catalog.html
> +      <div class="main-nav__wrapper">
В чём предназначение обёртки? По дизайну посмотрел, не смог увидеть необходимости.

2023-04-10 13:45 UTC, ZerdoX-x commented on catalog.html
> +            <a href="#">
Почему главная ведёт на `#`?

2023-04-10 13:45 UTC, ekhodx commented on catalog.html
> +          <li class="site-lisy__item site-list__item--current">
1. Опечатка в классе
2. `--current` модификатор нам пока не нужен. И в мобильном дизайне его тоже нет

2023-04-10 13:45 UTC, ZerdoX-x commented on catalog.html
> +              HTMl Academy
```suggestion
              HTML Academy
```

2023-04-10 13:45 UTC, ZerdoX-x commented on catalog.html
> +            <a href="photo-video.html">
Перепроверь пожалуйста все `href` на страницах, чтобы ссылки вели на соответствующие страницы

2023-04-10 13:45 UTC, ZerdoX-x commented on catalog.html
> +  <main class="main-container">
Не нашёл разметки для этого блока
<img width="602" alt="image" src="https://user-images.githubusercontent.com/49815452/230910275-e87b9dac-e868-4bd5-8260-ed1b4acf03af.png">

2023-04-10 13:45 UTC, ZerdoX-x commented on catalog.html
> +</head>
советую добавить `<meta name="viewport" content="width=device-width, initial-scale=1">`

2023-04-10 13:45 UTC, ekhodx commented on catalog.html
> +        Не можете решиться на путешествие из-за курса?<br>Фотографии помогут вам забыть о политике и экономике.
Для чего тут `<br>`?

2023-04-10 13:45 UTC, ekhodx commented on catalog.html
> +          <img class="labbelled-image__image" src="img/" width="1200px" height="400px" alt="Закат Седоны">
Перепроверь `src`, `width`, `height`

2023-04-10 13:45 UTC, ZerdoX-x commented on catalog.html
> +      </ul>
Почему в галерее только один элемент? В дизайне вижу 4.

2023-04-10 13:45 UTC, ekhodx commented on catalog.html
> +      <img class="video-info" src="img/" width="800px" height="500px" alt="Видео про Седону">
1) Указывай актуальные размеры. Это мобильная вёрстка. Перепроверь все размеры которые ты указывал в верстке на всех страницах.
2) Так как видео у нас нет, советую картинку обернуть в ссылку и указать например ютуб академии.

2023-04-10 21:39 UTC, ZerdoX-x requested changes

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +          <li class="site-lisy__item site-list__item--current">
блок `site-lisy`?

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
<img width="409" alt="image" src="https://user-images.githubusercontent.com/49815452/230980310-518bb3c7-c7d4-4f2c-a963-86406e0fe1fb.png">

Скриншот из домашнего задания

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +        <ul class="main-nav__list site-list">
Я бы подумал над названием блока `site-list`. Из названия не очень понятно, что из себя представляет этот блок...

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +            <a href="index.html">
Скорее всего стили будут и у `a`, так что добавь этому тегу тоже класс пожалуйста.

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +            <a href="photo-video.html">
`photo-video.html`? судя по тексту ссылка ведёт на академию

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +    <section class="video-photo">
Необходимо подумать над названием блока `video-photo`. В дизайне видно, что этот блок с одинаковыми стилями переиспользуется в разных частях сайта, но с разным контентом.

<img width="632" alt="image" src="https://user-images.githubusercontent.com/49815452/230982787-b2439d20-b82a-4f69-b843-69a7a8678cf9.png">
<img width="549" alt="image" src="https://user-images.githubusercontent.com/49815452/230982846-226274a6-c7e3-4f83-9513-eb993d8129e9.png">
<img width="443" alt="image" src="https://user-images.githubusercontent.com/49815452/230982894-e993ee2e-125b-42bd-acd8-cff8d1187b06.png">

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +    </section>
Также.. ты уверен, что данный блок стоит выносить в отдельный `section`? По дизайну можно сказать, что этот контент не является отдельной самостоятельной секцией, а описывает контент ниже и полностью с ним связан логически.

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +          <img class="labbelled-image__image" src="images/sunset.jpg" width="280" height="280" alt="Закат Седоны">
опечатка в названии блока: `labbelled-image`

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +          <img class="labbeled-image__likes-icon" src="images/like.svg" width="23" height="21" alt="Лайк">
опечатка в названии блока: `labbeled-image`

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +          <p class="labbeled-image__likes-counter">1350</p>
По семантике, кажется, здесь не очень уместен тег `p`

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +    <section class="video-photo">
Вот.. В данном случае блок вообще никак не описывает, что внутри него находится и это дело сейчас выглядит очень странно)

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +    <section class="video-photo">
То же и здесь, что в предыдущем использовании `video-photo`. Не думаю, что это является отдельной секцией. Это связанный друг с другом контент: этот блок, и блок ниже, с видео.

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +    <section class="video">
Если хочешь создать из этой секции блок по БЭМу, то стоит подумать над названием, но мне кажется этой секции даже не придётся задавать никаких стилей, и класс нам тут не очень нужен.

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +    <div class="main-footer__wrapper">
Тут какую функцию выполняет элемент wrapper? Не понял, зачем он нужен

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +          #Visitsedona
```suggestion
          #visitsedona
```
или
```suggestion
          #VISITSEDONA
```

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +        <ul class="socia__list">
опечатка в названии.... несуществующего блока `socia`?

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +        <b class="copyright__text">разработанно</b>
```suggestion
        <b class="copyright__text">Разработано</b>
```

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +            <a class="social_link" href="https://vk.com/htmlacademy">Мы в Вконтакте</a>
что такое `social_link`, а именно `_` здесь?

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +        <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive"></a>
Не хватает картинки. Плюс, я думаю мы можем отказаться от обёртки-дива `main-footer__copyright`, если сделаем это всё ссылкой (и текст тоже)
<img width="349" alt="image" src="https://user-images.githubusercontent.com/49815452/230989214-9f28a982-a78f-494a-819b-1c13c54e8d5b.png">

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +      <div class="main-footer__contacts">
Для чего эта обёртка? У нас все элементы списка и так объедены в один `ul`. Для чего понадобилась ещё обёртка над списком?

2023-04-10 21:39 UTC, ekhodx commented on catalog.html
> +      <div class="main-footer__tag">
В этом диве-обёртке тоже не могу найти функционал/смысл

2023-04-10 21:39 UTC, ekhodx commented on form.html
> +  </footer>
Где заканчивается `body` и `html`? Прогоняй весь код через валидатор пожалуйста, и исправляй все его ошибки. В этом PR хотелось бы акцентировать внимание именно на БЭМ и классах, которые ты пишешь по БЭМу

2023-04-10 21:39 UTC, ekhodx commented on source/index.html
> +    <h1 class="visualy-hidden">Седона - "По истинне уютный городок"
```suggestion
    <h1 class="visualy-hidden">Седона - "По истине уютный городок"
```

2023-04-10 21:39 UTC, ekhodx commented on source/index.html
> +        <h2 class="infromation_header">Седона — небольшой городок в Аризоне,<br>заслуживающий большего!</h2>
`_`?

`<br>` не нужен

2023-04-10 21:39 UTC, ekhodx commented on source/index.html
> +        <p class="infromation_slogan">Рассмотрим причины, по которым Седона круче, чем Гранд-Каньон!</p>
`_`?

2023-04-10 21:39 UTC, ekhodx commented on source/index.html
> +      <div class="information__wrapper">
Для чего нужен этот wrapper?

2023-04-10 21:39 UTC, ekhodx commented on source/index.html
> +      <ul class="description">
1) По-моему это упорядоченный список. По крайней мере в дизайне он пронумерован
2) Стоит подумать над названием класса/блока. По семантике и дизайну это **список преимуществ** (седоной над гранд каньоном). Ты представил это как "описание"

2023-04-10 21:39 UTC, ZerdoX-x commented on source/index.html
> +            <p class="advantages__info">Седона — не аттракцион для<br> туристов, там течёт своя<br>
Пока что убери все `br` на всех страницах, пожалуйста. Я думаю, они нам не понадобятся. Не нужно каждый перенос строки в дизайне отмечать `br`'ом.

2023-04-10 21:39 UTC, ZerdoX-x commented on source/index.html
> +          <img class="advantages__image__town" src="images/sedona-city.jpg" width="520" height="260"
Что это за монстр?) `advantages__image__town`
В БЭМ не существует элемента элемента, подумай над этим пожалуйста

2023-04-10 21:39 UTC, ZerdoX-x commented on source/index.html
> +          <p class="conditions__info conditions__info--housing">Рекомендуем пожить<br> в настоящем мотеле,<br> всё как в
Какую функцию выполняют модификаторы в этих блоках? `housing`, `food` и `present`

2023-04-10 21:39 UTC, ZerdoX-x commented on source/index.html
> +        <li class="advantages">
По этой строчке кажется, что `li` содержит в себе преимущества (множественные), хотя сам элемент списка - это одно из некоторых преимуществ. Этот комментарий связан с предыдущим, пожалуйста переработай нейминг классов в этой области.

2023-04-10 21:39 UTC, ZerdoX-x commented on source/index.html
> +      </ul>
Почему вдруг закончился список и начались дивы? Как ты определил, что список закончился именно после этого пункта?

2023-04-10 21:39 UTC, ZerdoX-x commented on source/index.html
> +    </section>
<img width="997" alt="image" src="https://user-images.githubusercontent.com/49815452/230999462-e0ffd3a8-bd68-4a0a-bf87-27be09f33aba.png">

Советую иногда смотреть на макет "сверху", отбрасывая верстку. Если оглянуть дизайн, становится понятно, что три пункта (жильё, еда, сувениры) - это список, который существует в рамках первого пункта (который рассказывает о том, что седона это полноценный и настоящий городок) "главного" или "родительского" списка (который перечисляет преимущества седоны над гранд каньоном).

2023-04-10 21:39 UTC, ZerdoX-x commented on source/index.html
> +    </section>
То есть у тебя есть "главный список", состоящий из 5 пунктов. И в контексте первого пункта этого списка раскрывается ещё один список из 3 пунктов. Посмотри, обдумай пожалуйста.

2023-04-10 21:39 UTC, ZerdoX-x commented on catalog.html
> +  </footer>
Не хватает закрытия `body` и `html`

2023-04-10 21:39 UTC, ZerdoX-x commented on source/index.html
> +      <a class="search__hotel" href="#">Найти гостниницу</a>
ссылаешься на несуществующий блок `search`

2023-04-10 21:39 UTC, ZerdoX-x commented on source/index.html
> +    <a class="main-footer__map">
элементы блока не могут находиться вне блока. у тебя элемент `map` существует мне блока `main-footer`. и я думаю, что карта всё же относится к секции "найти гостиницу", а не футеру

2023-04-10 21:39 UTC, ZerdoX-x commented on form.html
> +    </section>
Почему тег `form` использовался только кнопке и одном параграфе?
Все инпуты которые были выше тоже входят в эту форму. Пользователь заполняет все-все данные и потом отправляет всю эту форму. В форме и номер телефона, и посещённые места. Не только эмоции.

2023-04-10 21:39 UTC, ZerdoX-x commented on form.html
> +      <input class="emotions__text" placeholder="Опишите подробно все свои восторги" type="text" required>
Я думаю здесь можно использовать более подходящий тег для этого, не `input`
<img width="308" alt="image" src="https://user-images.githubusercontent.com/49815452/231002097-0ee35140-ff12-4797-a1c2-5d2433209dd0.png">

2023-04-10 21:39 UTC, ZerdoX-x commented on form.html
> +    </section>
Как ниже я уже описал, это всё - форма. Секции тут неуместны.

Почитай пожалуйста: https://doka.guide/html/section/ - *независимый* блок. У тебя все эти section на самом деле между собой связаны. Все они - элементы одной большой формы, которую заполняет пользователь.

2023-04-10 21:39 UTC, ZerdoX-x commented on form.html
> +        <label class="test__label" for="positive">Скорее положительное</label>
Советую вложить `input` внутрь `label`, чтобы не пришлось писать `for` и `id`, так код будет выглядеть поприятнее, и без создания ненужных айдишников, которые позже могут в теории аукнуться (например если ты про него забудешь и создашь другой элемент с таким же айди, и всё сломается)

2023-04-10 21:39 UTC, ekhodx commented on form.html
> +        <input class="number" placeholder="Введите телефон" type="tel" required>
`p` тут не очень подходит по семантике, и я советую обернуть этот текст и инпут в один `label`

2023-04-12 15:07 UTC, ZerdoX-x requested changes

2023-04-12 15:07 UTC, ekhodx commented on images/back-catalog.jpg
для чего два экспорта одной и той же картинки? я увидел и на странице "каталог" и на странице "форма" одинаковые картинки, с одинаковыми размерами

2023-04-12 15:07 UTC, ekhodx commented on images/back-index.jpg
Удали все дубликаты картинок, пожалуйста. Нам понадобится только одна, самая большая и сама полная картинка. На других страницах она просто будет подрезаться

2023-04-12 15:07 UTC, ekhodx commented on source/catalog.html
> +        <span class="visualy-hidden">Открыть меню</span>
Опечатки в классах `main-nav__toogle` и `visualy-hidden`

2023-04-12 15:07 UTC, ekhodx commented on images/logotype-phone.svg
Почему `phone`? И похоже, что-то не так с логотипом. Проверяй, что ты экспортируешь
<img width="160" alt="image" src="https://user-images.githubusercontent.com/49815452/231481923-6fb0cca9-f689-4052-ac05-177608300d93.png">

2023-04-12 15:07 UTC, ekhodx commented on source/catalog.html
> +            <a class="site-menu__link" href="academy.html">
Несуществующая страница, и у нас её не будет. Просто оставь здесь ссылку на академию, буквально, ссылка на академию в интернете.

2023-04-12 15:07 UTC, ekhodx commented on source/catalog.html
> +            <img class="site-menu__background" src="../images/back-catalog.jpg" width="900" height="390"
Картинка в навигации сайта? По-моему эта вёрстка не должна тут находиться
<img width="546" alt="image" src="https://user-images.githubusercontent.com/49815452/231482766-a1baa0d1-35d2-4d9c-8645-4a7a221f1436.png">

2023-04-12 15:07 UTC, ekhodx commented on source/catalog.html
> +    <section class="main-info-block">
Мы воспринимаем блок в БЭМ как переиспользуемый элемент интерфейса. У тебя в данном случае `main-info-block` - это целая секция с галереей внутри. В следующем случае (88 строка) - секция с видео.

Если ты хочешь переиспользовать блок и стили для заголовка и параграфа (`main-info-block__title` и `main-info-block__slogan`), то ты можешь вынести их в отдельный блок, обернуть в див например, внутри которого будет только заголовок и параграф

2023-04-12 15:07 UTC, ekhodx commented on source/catalog.html
> +    <section class="main-info-block">
Смотри предыдущий комментарий касательно `main-info-block`

2023-04-12 15:07 UTC, ekhodx commented on source/catalog.html
> +      <h1 class="main-info-block__title">
Это уже второй h1 на этой странице

https://doka.guide/html/h1-h6/#podskazki

2023-04-12 15:07 UTC, ekhodx commented on source/form.html
> +    </section>
Почему эта часть формы не включена в `form`? Заголовок и эти поля так же являются частью формы

2023-04-12 15:07 UTC, ekhodx commented on source/form.html
> +          <label class="contact__name">
`contact__title` и `contact__name` - элементы, у которых не существует блока `contact`, если посмотреть выше на родителей этих элементов

2023-04-12 15:07 UTC, ekhodx commented on source/form.html
> +        <div class="contact">
Для чего "контактный телефон" отделён от "электронной почты" дивами? Первый лежит в `form__contact`, второй в `contact`. Лишние обёртки. Вроде бы достаточно того, что они лежат в разных `label`.

2023-04-12 15:07 UTC, ekhodx commented on source/form.html
> +        <div class="test">
Вместо дивов следует разбить части формы на разные `section`, внутри которого будет по одному заголовку.

По дизайну вижу 5 секций (ФИО, контакты, впечатление, достопримечательности, эмоции)
<img width="198" alt="image" src="https://user-images.githubusercontent.com/49815452/231490649-c28fdd3f-16a4-4bcf-b3cc-349743162f58.png">

А вот эта часть - заголовок и описание всей формы, ниже которых будут идти вышеперечисленные секции
<img width="264" alt="image" src="https://user-images.githubusercontent.com/49815452/231491302-a1d5d7b3-a2ae-477f-8423-25a1c5183975.png">

2023-04-12 15:07 UTC, ekhodx commented on source/form.html
> +        <div class="attractions">
Также... Для чего _(в будущем, как ты исправишь)_ секциям заданы подобные уникальные классы? `attractions`, `test`, `emotion`. По дизайну видно, что каждая секция это один и тот же блок (секция формы), у которых одинаковые стили: серая рамка, заголовок, отступ от заголовка до элементов формы.

2023-04-12 15:07 UTC, ekhodx commented on source/form.html
> +          </label>
`for` и `id` в данном случае следует опустить. `input` и так находится внутри `label`, к которому он привязан.

2023-04-12 15:07 UTC, ekhodx commented on source/form.html
> +          <label class="attractionsx__label" for="bridge">
Если я правильно понимаю, то `attractionsx__label` содержит опечатку.

2023-04-12 15:07 UTC, ekhodx commented on source/form.html
> +          </label>
То же, что и выше. `for` и `id` следует опустить.

2023-04-12 15:07 UTC, ekhodx commented on source/form.html
> +          <textarea class="emotion__text" placeholder="Опишите подробно все свои восторги" required></textarea>
Почему данный `textarea` - required?

2023-04-12 15:07 UTC, ekhodx commented on source/form.html
> +        <ul class="socia__list">
Актуализируй футер. Тут и на странице `index` опечатка, хотя на `catalog` её нет. И лишние дивы тут тоже присутствуют, которых нет на странице catalog.

На странице каталога тоже оставил пару комментариев по коду актульного футера, как закончишь работу над ним, скопируй на все страницы.

2023-04-12 15:07 UTC, ekhodx commented on source/catalog.html
> +    <div class="main-footer__tag">
Для чего оборачивать `a` в `div`?

2023-04-12 15:07 UTC, ekhodx commented on source/catalog.html
> +    </a>
Картинка идёт после текста
<img width="246" alt="image" src="https://user-images.githubusercontent.com/49815452/231495022-ff11153b-b13f-44dc-af2d-722737a296de.png">

2023-04-12 15:07 UTC, ekhodx commented on source/catalog.html
> +    </ul>
Ссылаешься на несуществующий блок `social`

2023-04-12 15:07 UTC, ekhodx commented on source/catalog.html
> +    <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive">
Ссылаешься на несуществующий блок `copyright`

2023-04-12 15:07 UTC, ekhodx commented on source/index.html
> +  <main class="main-container">
У этого блока будет разметка?
<img width="356" alt="image" src="https://user-images.githubusercontent.com/49815452/231496400-1804089a-bd2d-461c-bfc1-b13000263984.png">

2023-04-12 15:07 UTC, ekhodx commented on source/index.html
> +    </section>
Теперь стало получше, вместо дивов вижу список из 8 элементов. Но пожалуйста, внимательно прочитай, что я написал выше. "жильё", "еда" и "сувениры" это **подсписок**.

2023-04-12 15:07 UTC, ekhodx commented on source/index.html
> +            <h3 class="advantages__title">Там естьмост дьявола</h3>
```suggestion
            <h3 class="advantages__title">Там есть мост дьявола</h3>
```

2023-04-12 15:07 UTC, ekhodx commented on source/index.html
> +      </p>
Этот заголовок и параграф должны напоминать кое-какой блок. Касательно него уже были комментарии на предыдущих страницах, где ты его вынес в секцию `main-info-block`

2023-04-12 15:07 UTC, ekhodx commented on source/index.html
> +  <footer class="main-footer">
Актуализируй футер.

2023-04-12 15:07 UTC, ZerdoX-x commented on source/index.html
И ещё, проверь пожалуйста, что у тебя все картинки загружаются. Я видел некоторые неактуалные пути для в `src`. Ты можешь открыть каждую страницу, открыть вкладку `network` или просто консоль, и там увидеть все 404 ошибки

2023-04-14 15:14 UTC, markfswe requested changes

2023-04-14 15:14 UTC, ekhodx commented on source/catalog.html
> +    <div class="site-menu__item">
что значит класс `site-menu__item`? у элемента отсутсвует родитель-блок `site-menu`. и не похоже, чтобы эта вёрстка хоть как-то относилась к навигации по сайту

и вроде бы, этой вёрстке не место в шапке. плюс, ты использовал здесь svg, который не подходит к этой странице

<img width="655" alt="image" src="https://user-images.githubusercontent.com/49815452/232080570-337de812-d263-4c2d-b513-443012f51651.png">

ты когда верстаешь, сравнивай свою страницу которую ты делаешь, с тем, что находится в макете пожалуйста

2023-04-14 15:14 UTC, ekhodx commented on source/catalog.html
> +    Разработано
текст и картинка кажется выпали из ссылки..

2023-04-14 15:14 UTC, ZerdoX-x commented on source/form.html
> +    <section class="feedback">
я думаю в данном случае следует опустить `section`. он часто используется чтобы отделить независимые части контента друг от друга, у нас здесь внутри лежит только одна форма и в `main` у нашего `section` даже нет других соседей

2023-04-14 15:14 UTC, ZerdoX-x commented on source/form.html
> +        <section class="data">
секция - это элемент формы

2023-04-14 15:14 UTC, ZerdoX-x commented on source/form.html
> +    <section class="feedback">
и я бы переименовал блок feedback в блок form.
в теории мы хотим стили для этих блоков переиспользовать, и в теории не каждую форму можно назвать фидбеком

2023-04-14 15:14 UTC, ekhodx commented on source/form.html
> +          <h2 class="data__title">Представьтесь:</h2>
заголовок секции, это элемент формы

то же самое с инпутам, лейблами и всеми другими элементами формы

2023-04-14 15:14 UTC, ZerdoX-x commented on source/form.html
> +          <input class="name" placeholder="Ваше имя" type="text" required>
у инпутов не хватает аттрибута name. узнай, что за аттрибут и как его использовать, чтобы поставить ему правильное значение

2023-04-14 15:14 UTC, ZerdoX-x commented on source/index.html
> +        <li class="advantages">
Почему ты закрываешь неразрешённые комментарии?) Тут же проблема не была исправлена

2023-04-14 15:14 UTC, ZerdoX-x commented on source/index.html
> +        <div class="services">
html валидатор: нельзя вкладывать `div` в `ul`

2023-04-14 15:14 UTC, ZerdoX-x commented on source/index.html
> +          <h3 class="onditions__title">Мало туристов</h3>
опечатка `onditions__title` (и не только в этом месте)

2023-04-14 19:06 UTC, ZerdoX-x commented on images/back.jpg
<img width="622" alt="image" src="https://user-images.githubusercontent.com/49815452/232134369-cddc7fe5-4274-4b84-afdf-e276c72044c0.png">

2023-04-21 19:58 UTC, ZerdoX-x commented
То, что доработаем позже: (продублировал из переписки в тг)

1) картинку обрезанную скачал, не полную
2) `main-info-block` - не понятно что за блок (мы его на созвоне уже разбирали). заголовок и параграф не переиспользует стили. такие же заголовки и параграфы используются на всём проекте
3) visualy-hidden - опечатка или грамматическая ошибка в классе
4) на каждой странице по 2 `h1`. смотри предупреждение от валидатора на скрине и например вот дока: https://doka.guide/html/h1-h6/

index.html:
5) по дизайну и семантике вложенный список (62 строка) не является упорядоченным. если поменять элементы местами, ничего не изменится
6) строки 63 и 69: `service__conditions` и `condition` почему разные классы у по факту одного и того же блока? плюс у первого `li` на 63 строке внутри получаются невалидные элементы, блок `condition` не существует
7) то же самое про корневой список. идёт 5 преимуществ, одинаковых блоков по идее, но у них разные классы: `advantage`, `advantages`, `conditions`

2023-04-21 20:00 UTC, ZerdoX-x approved these changes

2023-04-21 20:00 UTC, merged